# Generated by Django 6.0.4 on 2026-04-20 13:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="product_images/")),
                ("description", models.TextField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Cap", "Capsules"),
                            ("Pow", "Powders"),
                            ("Tab", "Tablets"),
                            ("Liq", "Liquids"),
                        ],
                        max_length=3,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("stock", models.IntegerField()),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
    ]
